import { InscripcionData } from '../inscripcion.page';

export function createEmptyInscripcionData(): InscripcionData {
  return {
    firstName: '',
    lastName: '',
    dni: '',
    birthDate: '',
    age: null,
    address: '',
    locality: '',
    province: '',
    phone: '',
    email: '',
    category: '',
    subcategory: '',
    members: [],
    artisticName: '',
    themes: [
      { title: '', rhythm: '', author: '' },
      { title: '', rhythm: '', author: '' },
    ],
    riderTecnico: {
      sonido: {
        microfonos: [],
        diBoxes: null,
        cables: [],
        backline: [],
      },
      inputList: [],
      monitorCount: 0,
      monitorMixes: [],
      stagePlotInstruments: [],
      otros: '',
    },
    equipmentDesc: '',
    stagePlotDesc: '',
    proposalName: '',
    choreographerName: '',
    style: '',
    danceList: '',
    biography: '',
    dniFrontFile: null,
    dniBackFile: null,
    promoPhotoFile: null,
    lyricsFile: null,
    scoreFile: null,
    dniFrontName: '',
    dniBackName: '',
    promoPhotoName: '',
    lyricsFileName: '',
    scoreFileName: '',
    acceptRegulations: false,
    acceptImageRights: false,
    acceptDataTruth: false,
    acceptNoPriorWin: false,
    acceptNotJurorOrg: false,
    acceptPurelyInstrumental: false,
    acceptOneInstrument: false,
    acceptNoPrerecorded: false,
    acceptNoInstrumentChange: false,
    presentation: '',
    songsList: '',
    instrumentType: '',
    instrumentName: '',
    hasAccompaniment: false,
    accompanimentInstrument: '',
    accompanimentMusician: '',
    danceStyle: '',
    danceThemes: [
      { title: '', song: '' },
      { title: '', song: '' },
      { title: '', song: '' },
    ],
    danceMp3File: null,
    danceMp3FileName: '',
    workTitle: '',
    assistantsCount: 0,
    bandMembers: [],
    accompanyingPersons: [],
  };
}
